language: node_js
cache: yarn
node_js:
  - 'stable'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
script:
  - npm run flow -- check
  - npm run lint
