name: Check versions
on:
  issues:
    types: [opened]

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: react-navigation/check-versions-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          required-packages: |
            react-native-tab-view
            react-native-gesture-handler
            react-native-reanimated
